# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30735a5b15891e86a4a5995a4d6f8524fe4baa82eadcb0079e6054ebd1b4869e5b75b75d2e0b99135ef5a8f218ab79a06a457339641e4019f7a11075609ecc6d

test:
  secret_key_base: 3b97e2ce9ae8441e670da26c2eb51074dfbfd8919aa777548a467413f7d862c0413ce2eb03c8bc84e75175f08baac9ce74772ac8057d01e90d02f44cbc04bd5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
